program pismeno;
uses crt;
const x=20;       {vodorovna pozice}
      a=40;       {sirka}
      a2=20;      {polovina sirky}
      y=2;        {svisla pozice}
      b=20;       {vyska}
      b2=10;      {polovina vysky}
      z=77;       {znak}
label start,konec;
begin
clrscr;
{--------------------------------------------------------}
asm
start:

konec:
end;
{--------------------------------------------------------}
repeat until keypressed;
end.
