CREATE TABLE [Zaci] (
	[id] INTEGER NOT NULL UNIQUE,
	[trida] INTEGER,
	PRIMARY KEY([id])
);
GO

CREATE TABLE [Znamky] (
	[id] INTEGER NOT NULL IDENTITY UNIQUE,
	[id_zak] INTEGER NOT NULL,
	[datum] DATE NOT NULL DEFAULT getdate(),
	[absence] BIT NOT NULL DEFAULT 0,
	[znamka] INTEGER NOT NULL DEFAULT 0 CHECK([znamka] >= 0 AND [znamka] <= 5),
	[vaha] INTEGER NOT NULL DEFAULT 5 CHECK([vaha] >= 1 AND [vaha] <= 10),
	[id_predmet] INTEGER NOT NULL,
	PRIMARY KEY([id])
);
GO

CREATE TABLE [Predmety] (
	[id] INTEGER NOT NULL IDENTITY UNIQUE,
	[nazev] VARCHAR(10) NOT NULL,
	[vyucujici] INTEGER NOT NULL,
	PRIMARY KEY([id])
);
GO

CREATE TABLE [Ucitele] (
	[id] INTEGER NOT NULL UNIQUE,
	PRIMARY KEY([id])
);
GO

CREATE TABLE [Osoby] (
	[id] INTEGER NOT NULL IDENTITY UNIQUE,
	[jmeno] NVARCHAR(100) NOT NULL,
	[prijmeni] NVARCHAR(100) NOT NULL,
	PRIMARY KEY([id])
);
GO

CREATE TABLE [Tel_cisla] (
	[cislo] INTEGER NOT NULL UNIQUE,
	[id_osoby] INTEGER NOT NULL,
	PRIMARY KEY([cislo])
);
GO

CREATE TABLE [Tridy] (
	[id] INTEGER NOT NULL UNIQUE,
	[nazev] VARCHAR(10) NOT NULL,
	[tridni_ucitel] INTEGER,
	PRIMARY KEY([id])
);
GO


ALTER TABLE [Znamky]
ADD FOREIGN KEY([id_zak])
REFERENCES [Zaci]([id])
ON UPDATE NO ACTION ON DELETE NO ACTION;
GO
ALTER TABLE [Znamky]
ADD FOREIGN KEY([id_predmet])
REFERENCES [Predmety]([id])
ON UPDATE NO ACTION ON DELETE NO ACTION;
GO
ALTER TABLE [Predmety]
ADD FOREIGN KEY([vyucujici])
REFERENCES [Ucitele]([id])
ON UPDATE NO ACTION ON DELETE NO ACTION;
GO
ALTER TABLE [Zaci]
ADD FOREIGN KEY([id])
REFERENCES [Osoby]([id])
ON UPDATE NO ACTION ON DELETE NO ACTION;
GO
ALTER TABLE [Ucitele]
ADD FOREIGN KEY([id])
REFERENCES [Osoby]([id])
ON UPDATE NO ACTION ON DELETE NO ACTION;
GO
ALTER TABLE [Tel_cisla]
ADD FOREIGN KEY([id_osoby])
REFERENCES [Osoby]([id])
ON UPDATE NO ACTION ON DELETE NO ACTION;
GO
ALTER TABLE [Tridy]
ADD FOREIGN KEY([tridni_ucitel])
REFERENCES [Ucitele]([id])
ON UPDATE NO ACTION ON DELETE NO ACTION;
GO
ALTER TABLE [Zaci]
ADD FOREIGN KEY([trida])
REFERENCES [Tridy]([id])
ON UPDATE NO ACTION ON DELETE NO ACTION;
GO